Update reference data scripts to handle more failure situations more gracefully.
My bash skills are not very impressive, but this is not rocket science either.

diff --git a/test/regression/scripts/upload b/test/regression/scripts/upload
--- a/test/regression/scripts/upload
+++ b/test/regression/scripts/upload
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2013 Anders Logg
+# Copyright (C) 2013 Anders Logg and Martin Sandve Alnaes
 #
 # This file is part of FFC.
 #
@@ -17,43 +17,26 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with FFC. If not, see <http://www.gnu.org/licenses/>.
 #
-# Modified by Martin Sandve Alnaes, 2013-08-20
-#
 # First added:  2013-04-22
-# Last changed: 2013-08-20
+# Last changed: 2013-08-21
 #
 # This script overwrites the reference data with the current output
 # and stores the new reference data as part of the FFC reference data
-# repository.
+# repository. The commit id of the stored reference data is commited
+# to a file in the main repo.
 
 # Parameters
 source ./scripts/parameters
 
-# Check that we have any data
-if [ ! -d $OUTPUT_DIR ]; then
-    echo "Can't find data directory '$OUTPUT_DIR'."
+# Get updated reference repository
+./scripts/getreferencerepo
+if [ $? -ne 0 ]; then
     exit 1
 fi
 
-# Get current id for main repo (does not include dirty files!)
-REPO_ID=`git rev-list --max-count 1 HEAD`
-
-# Get reference repository
-if [ ! -d $DATA_DIR ]; then
-    echo "Cloning reference data repository"
-    git clone $DATA_REPO_GIT
-    if [ ! -d $DATA_DIR ]; then
-        git clone $DATA_REPO_HTTPS
-    fi
-else
-    echo "Found existing reference data repository, pulling new data"
-    (cd $DATA_DIR && git checkout master && git pull)
-    # FIXME: What if there is a merge happening here?
-fi
-
-# Check that we had success with getting reference repository
-if [ ! -d $DATA_DIR ]; then
-    echo "Can't clone reference data directory '$DATA_DIR'."
+# Check that we have any data
+if [ ! -d "$OUTPUT_DIR" ]; then
+    echo "Missing data directory '$OUTPUT_DIR'."
     exit 1
 fi
 
@@ -62,15 +45,28 @@ echo "Copying new reference data to $DATA_DIR"
 rsync -r  --exclude='README.rst' --exclude='*.bin' --exclude='*.cpp' $OUTPUT_DIR/ $DATA_DIR
 echo ""
 
-# Commit and push data repository
-cd $DATA_DIR
+# Get current id for main repo (does not include dirty files, so not quite trustworthy!)
+REPO_ID=`git rev-list --max-count 1 HEAD`
+
+# Commit new data to reference repository
+pushd $DATA_DIR
 git add *
 git commit -m "Update reference data, current project head is ${REPO_ID}." | grep -v "create mode"
+if [ $? -ne 0 ]; then
+    echo "Failed to commit reference data."
+    exit 1
+fi
 DATA_ID=`git rev-list --max-count 1 HEAD`
-git push
-cd ..
+popd
 
-# Commit data id
+# Commit reference data commit id to file in main repo
 echo $DATA_ID > $DATA_ID_FILE
 git commit $DATA_ID_FILE -m"Update reference data pointer to ${DATA_ID}."
 
+# Push references to server
+pushd $DATA_DIR
+git push
+if [ $? -ne 0 ]; then
+    echo "WARNING: Failed to push new reference data to server."
+fi
+popd
