Tailorized "2005-12-28 21:44:39 by logg" Don't compile Stabilization.form as part of verification.
Takes too long to compile (generating the code). The computation
of the reference tensor is very fast, about 1.5 seconds.

diff --git a/scripts/verify b/scripts/verify
--- a/scripts/verify
+++ b/scripts/verify
@@ -7,12 +7,14 @@ cd src/demo
 for f in *.form; do
     PREFIX=`echo $f | cut -d'.' -f1`
     rm -f $PREFIX.h
-    ../bin/ffc $f
-    if [ -f $PREFIX.h ]; then
-	echo "Form $f compiled"
-    else
-	echo "*** Unable to compile $f"
-	exit 1
+    if [ $f != 'Stabilization.form' ]; then
+      ../bin/ffc $f
+      if [ -f $PREFIX.h ]; then
+	  echo "Form $f compiled"
+      else
+	  echo "*** Unable to compile $f"
+	  exit 1
+      fi
     fi
 done
 
